# Generated by Django 3.0.4 on 2020-03-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20200323_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
